---
title: "figure4"
author: "maggie weatherly"
date: "2/23/2020"
output: pdf_document
---


```{r, echo=F}
df <- data %>% select(is_fake_news, num_hashtags) 

ggplot(df, aes(num_hashtags)) +
  geom_histogram(aes(y=c(..count..[..group..==2]/sum(..count..[..group..==2]),
                         ..count..[..group..==1]/sum(..count..[..group..==1]))*100,
                     color = is_fake_news, fill=is_fake_news),
                 position="dodge", bins=10, alpha = 0.4) +
  ylab("Percentage") + xlab("Number of Hashtags") +
  scale_color_manual(values = c("#df6066", "#80bab4"), labels = c("Fake News","Other")) +
  scale_fill_manual(values = c( "#df6066", "#80bab4"), labels = c("Fake News","Other")) +
  scale_x_continuous(breaks = seq(0,10,1), labels = seq(0,10,1)) +
  theme(panel.grid.minor = element_blank()) 
```


## Process of Figure 4 Replication

Figure 4 was a relatively simple figure to replicate. Using the supporting figure description, x-axis title and y-axis title, it was fairly straightforward when it came to replication. In the paper, "Characterizing Political Fake News in Twitter", Figure 4 depicts a histogram of all tweets in the dataset, segmented into two groups, Fake News and Other, and then binned by the number of hashtags they contained. In traditional histograms, the y-axis corresponds to county, however, in Figure 4, the y-axis corresponds to the percentage of tweets of a group (Fake News or Other) that fell into that specific bin of number of hashtags. It was then easy to then apply ggplot and geom_histogram functions on the dataset to get an almost identical figure to the one produced in the paper. Since the style of the two figures vary slightly, it is proably safe to assume that the authors of the paper used different or additional libraries to generate Figure 4.

