---
title: Repeoducibility of "Characterizing Political Fake News in Twitter"
author: Andy De La Fuente, Anmol Srivastava, Juan Solorio, Maggie Weatherly, Matt Rhodes
date: "`r format(Sys.time(),'%d %B, %Y')`"
bibliography: ../Notes/citations.bib
output:
  tufte::tufte_html: default
  tufte::tufte_handout:
    citation_package: natbib
    latex_engine: xelatex
  tufte::tufte_book:
    citation_package: natbib
    latex_engine: xelatex
link-citations: yes
---

```{r, libraries, echo=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
library(dplyr)
data <- read.csv(file = "../DATA/electionday_tweets_clean.csv")
```

```{r child-table1, child='Table 1.R'}
```

```{r child-figure4, child='figure4.Rmd'}
df <- data %>% select(is_fake_news, num_hashtags)
ggplot(df, aes(num_hashtags)) +
  geom_histogram(aes(y=c(..count..[..group..==1]/sum(..count..[..group..==1]),
                         ..count..[..group..==2]/sum(..count..[..group..==2]))*100,
                     color = is_fake_news, fill=is_fake_news),
                 position="dodge", bins=10, alpha = 0.4) +
  ylab("Percentage") + xlab("Number of Hashtags") +
  scale_color_manual(values = c("#df6066", "#80bab4")) +
  scale_fill_manual(values = c("#df6066", "#80bab4")) +
  scale_x_continuous(breaks = seq(0,10,1), labels = seq(0,10,1)) +
  theme(panel.grid.minor = element_blank())
```


```{r child-figure7, child='Figure7.Rmd'}
```



# References cited

[@TweetsOriginal]